# Generated by Django 4.0.5 on 2022-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('video_id', models.CharField(max_length=300, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='media/songs')),
                ('image', models.FileField(blank=True, null=True, upload_to='media/songs')),
                ('author', models.CharField(max_length=300, null=True)),
                ('publish_date', models.CharField(max_length=300, null=True)),
                ('length', models.CharField(max_length=300, null=True)),
                ('thumbnail_url', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
