# Generated by Django 4.0.5 on 2022-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
